// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { actionsTools } from "../../tools/actions.js";

const mockRequest = vi.mocked(githubRequest);

describe("actionsTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 184 tools", () => {
    expect(actionsTools).toHaveLength(184);
  });

  it("has no duplicate tool names", () => {
    const names = actionsTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_actions_get_actions_cache_retention_limit_for_enterprise", () => {
    const tool = actionsTools.find((t: any) => t.name === "github_actions_get_actions_cache_retention_limit_for_enterprise")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_actions_get_actions_cache_retention_limit_for_enterprise");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_actions_set_actions_cache_retention_limit_for_enterprise", () => {
    const tool = actionsTools.find((t: any) => t.name === "github_actions_set_actions_cache_retention_limit_for_enterprise")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_actions_set_actions_cache_retention_limit_for_enterprise");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("PUT");
    });
  });

  describe("github_actions_get_actions_cache_storage_limit_for_enterprise", () => {
    const tool = actionsTools.find((t: any) => t.name === "github_actions_get_actions_cache_storage_limit_for_enterprise")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_actions_get_actions_cache_storage_limit_for_enterprise");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
