// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { agentTasksTools } from "../../tools/agent-tasks.js";

const mockRequest = vi.mocked(githubRequest);

describe("agentTasksTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 5 tools", () => {
    expect(agentTasksTools).toHaveLength(5);
  });

  it("has no duplicate tool names", () => {
    const names = agentTasksTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_agent_tasks_list_tasks_for_repo", () => {
    const tool = agentTasksTools.find((t: any) => t.name === "github_agent_tasks_list_tasks_for_repo")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_agent_tasks_list_tasks_for_repo");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", per_page: 1, page: 1 });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_agent_tasks_create_task", () => {
    const tool = agentTasksTools.find((t: any) => t.name === "github_agent_tasks_create_task")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_agent_tasks_create_task");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

  describe("github_agent_tasks_get_task_by_repo_and_id", () => {
    const tool = agentTasksTools.find((t: any) => t.name === "github_agent_tasks_get_task_by_repo_and_id")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_agent_tasks_get_task_by_repo_and_id");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", task_id: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
