// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { appsTools } from "../../tools/apps.js";

const mockRequest = vi.mocked(githubRequest);

describe("appsTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 37 tools", () => {
    expect(appsTools).toHaveLength(37);
  });

  it("has no duplicate tool names", () => {
    const names = appsTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_apps_get_authenticated", () => {
    const tool = appsTools.find((t: any) => t.name === "github_apps_get_authenticated")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_apps_get_authenticated");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({  });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_apps_create_from_manifest", () => {
    const tool = appsTools.find((t: any) => t.name === "github_apps_create_from_manifest")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_apps_create_from_manifest");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ code: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

  describe("github_apps_get_webhook_config_for_app", () => {
    const tool = appsTools.find((t: any) => t.name === "github_apps_get_webhook_config_for_app")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_apps_get_webhook_config_for_app");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({  });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
