// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { classroomTools } from "../../tools/classroom.js";

const mockRequest = vi.mocked(githubRequest);

describe("classroomTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 6 tools", () => {
    expect(classroomTools).toHaveLength(6);
  });

  it("has no duplicate tool names", () => {
    const names = classroomTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_classroom_get_an_assignment", () => {
    const tool = classroomTools.find((t: any) => t.name === "github_classroom_get_an_assignment")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_classroom_get_an_assignment");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ assignment_id: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_classroom_list_accepted_assignments_for_an_assignment", () => {
    const tool = classroomTools.find((t: any) => t.name === "github_classroom_list_accepted_assignments_for_an_assignment")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_classroom_list_accepted_assignments_for_an_assignment");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ assignment_id: "test-value", page: 1, per_page: 1 });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_classroom_get_assignment_grades", () => {
    const tool = classroomTools.find((t: any) => t.name === "github_classroom_get_assignment_grades")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_classroom_get_assignment_grades");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ assignment_id: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
