// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { codeSecurityTools } from "../../tools/code-security.js";

const mockRequest = vi.mocked(githubRequest);

describe("codeSecurityTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 20 tools", () => {
    expect(codeSecurityTools).toHaveLength(20);
  });

  it("has no duplicate tool names", () => {
    const names = codeSecurityTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_code_security_get_configurations_for_enterprise", () => {
    const tool = codeSecurityTools.find((t: any) => t.name === "github_code_security_get_configurations_for_enterprise")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_code_security_get_configurations_for_enterprise");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", per_page: 1, before: "test" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_code_security_create_configuration_for_enterprise", () => {
    const tool = codeSecurityTools.find((t: any) => t.name === "github_code_security_create_configuration_for_enterprise")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_code_security_create_configuration_for_enterprise");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

  describe("github_code_security_get_default_configurations_for_enterprise", () => {
    const tool = codeSecurityTools.find((t: any) => t.name === "github_code_security_get_default_configurations_for_enterprise")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_code_security_get_default_configurations_for_enterprise");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
