// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { codesOfConductTools } from "../../tools/codes-of-conduct.js";

const mockRequest = vi.mocked(githubRequest);

describe("codesOfConductTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 2 tools", () => {
    expect(codesOfConductTools).toHaveLength(2);
  });

  it("has no duplicate tool names", () => {
    const names = codesOfConductTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_codes_of_conduct_get_all_codes_of_conduct", () => {
    const tool = codesOfConductTools.find((t: any) => t.name === "github_codes_of_conduct_get_all_codes_of_conduct")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_codes_of_conduct_get_all_codes_of_conduct");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({  });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_codes_of_conduct_get_conduct_code", () => {
    const tool = codesOfConductTools.find((t: any) => t.name === "github_codes_of_conduct_get_conduct_code")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_codes_of_conduct_get_conduct_code");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ key: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
