// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { codespacesTools } from "../../tools/codespaces.js";

const mockRequest = vi.mocked(githubRequest);

describe("codespacesTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 48 tools", () => {
    expect(codespacesTools).toHaveLength(48);
  });

  it("has no duplicate tool names", () => {
    const names = codespacesTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_codespaces_list_in_organization", () => {
    const tool = codespacesTools.find((t: any) => t.name === "github_codespaces_list_in_organization")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_codespaces_list_in_organization");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", per_page: 1, page: 1 });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_codespaces_set_codespaces_access", () => {
    const tool = codespacesTools.find((t: any) => t.name === "github_codespaces_set_codespaces_access")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_codespaces_set_codespaces_access");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("PUT");
    });
  });

  describe("github_codespaces_set_codespaces_access_users", () => {
    const tool = codespacesTools.find((t: any) => t.name === "github_codespaces_set_codespaces_access_users")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_codespaces_set_codespaces_access_users");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

});
