// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { copilotTools } from "../../tools/copilot.js";

const mockRequest = vi.mocked(githubRequest);

describe("copilotTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 25 tools", () => {
    expect(copilotTools).toHaveLength(25);
  });

  it("has no duplicate tool names", () => {
    const names = copilotTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_copilot_copilot_enterprise_one_day_usage_metrics", () => {
    const tool = copilotTools.find((t: any) => t.name === "github_copilot_copilot_enterprise_one_day_usage_metrics")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_copilot_copilot_enterprise_one_day_usage_metrics");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", day: "test" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_copilot_copilot_enterprise_usage_metrics", () => {
    const tool = copilotTools.find((t: any) => t.name === "github_copilot_copilot_enterprise_usage_metrics")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_copilot_copilot_enterprise_usage_metrics");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_copilot_copilot_users_one_day_usage_metrics", () => {
    const tool = copilotTools.find((t: any) => t.name === "github_copilot_copilot_users_one_day_usage_metrics")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_copilot_copilot_users_one_day_usage_metrics");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", day: "test" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
