// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { credentialsTools } from "../../tools/credentials.js";

const mockRequest = vi.mocked(githubRequest);

describe("credentialsTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 1 tools", () => {
    expect(credentialsTools).toHaveLength(1);
  });

  it("has no duplicate tool names", () => {
    const names = credentialsTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_credentials_revoke", () => {
    const tool = credentialsTools.find((t: any) => t.name === "github_credentials_revoke")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_credentials_revoke");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

});
