// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { dependencyGraphTools } from "../../tools/dependency-graph.js";

const mockRequest = vi.mocked(githubRequest);

describe("dependencyGraphTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 3 tools", () => {
    expect(dependencyGraphTools).toHaveLength(3);
  });

  it("has no duplicate tool names", () => {
    const names = dependencyGraphTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_dependency_graph_diff_range", () => {
    const tool = dependencyGraphTools.find((t: any) => t.name === "github_dependency_graph_diff_range")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_dependency_graph_diff_range");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", basehead: "test-value", name: "test" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_dependency_graph_export_sbom", () => {
    const tool = dependencyGraphTools.find((t: any) => t.name === "github_dependency_graph_export_sbom")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_dependency_graph_export_sbom");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_dependency_graph_create_repository_snapshot", () => {
    const tool = dependencyGraphTools.find((t: any) => t.name === "github_dependency_graph_create_repository_snapshot")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_dependency_graph_create_repository_snapshot");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

});
