// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { dependabotTools } from "../../tools/dependabot.js";

const mockRequest = vi.mocked(githubRequest);

describe("dependabotTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 22 tools", () => {
    expect(dependabotTools).toHaveLength(22);
  });

  it("has no duplicate tool names", () => {
    const names = dependabotTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_dependabot_list_alerts_for_enterprise", () => {
    const tool = dependabotTools.find((t: any) => t.name === "github_dependabot_list_alerts_for_enterprise")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_dependabot_list_alerts_for_enterprise");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", classification: "test", state: "test" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_dependabot_repository_access_for_org", () => {
    const tool = dependabotTools.find((t: any) => t.name === "github_dependabot_repository_access_for_org")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_dependabot_repository_access_for_org");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", page: 1, per_page: 1 });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_dependabot_update_repository_access_for_org", () => {
    const tool = dependabotTools.find((t: any) => t.name === "github_dependabot_update_repository_access_for_org")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_dependabot_update_repository_access_for_org");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("PATCH");
    });
  });

});
