// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { emojisTools } from "../../tools/emojis.js";

const mockRequest = vi.mocked(githubRequest);

describe("emojisTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 1 tools", () => {
    expect(emojisTools).toHaveLength(1);
  });

  it("has no duplicate tool names", () => {
    const names = emojisTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_emojis_get", () => {
    const tool = emojisTools.find((t: any) => t.name === "github_emojis_get")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_emojis_get");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({  });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
