// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { enterpriseTeamOrganizationsTools } from "../../tools/enterprise-team-organizations.js";

const mockRequest = vi.mocked(githubRequest);

describe("enterpriseTeamOrganizationsTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 6 tools", () => {
    expect(enterpriseTeamOrganizationsTools).toHaveLength(6);
  });

  it("has no duplicate tool names", () => {
    const names = enterpriseTeamOrganizationsTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_enterprise_team_organizations_get_assignments", () => {
    const tool = enterpriseTeamOrganizationsTools.find((t: any) => t.name === "github_enterprise_team_organizations_get_assignments")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_enterprise_team_organizations_get_assignments");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", enterprise_team: "test-value", per_page: 1, page: 1 });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_enterprise_team_organizations_bulk_add", () => {
    const tool = enterpriseTeamOrganizationsTools.find((t: any) => t.name === "github_enterprise_team_organizations_bulk_add")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_enterprise_team_organizations_bulk_add");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", enterprise_team: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

  describe("github_enterprise_team_organizations_bulk_remove", () => {
    const tool = enterpriseTeamOrganizationsTools.find((t: any) => t.name === "github_enterprise_team_organizations_bulk_remove")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_enterprise_team_organizations_bulk_remove");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", enterprise_team: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

});
