// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { gitTools } from "../../tools/git.js";

const mockRequest = vi.mocked(githubRequest);

describe("gitTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 13 tools", () => {
    expect(gitTools).toHaveLength(13);
  });

  it("has no duplicate tool names", () => {
    const names = gitTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_git_create_blob", () => {
    const tool = gitTools.find((t: any) => t.name === "github_git_create_blob")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_git_create_blob");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

  describe("github_git_get_blob", () => {
    const tool = gitTools.find((t: any) => t.name === "github_git_get_blob")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_git_get_blob");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", file_sha: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_git_create_commit", () => {
    const tool = gitTools.find((t: any) => t.name === "github_git_create_commit")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_git_create_commit");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

});
