// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { gitignoreTools } from "../../tools/gitignore.js";

const mockRequest = vi.mocked(githubRequest);

describe("gitignoreTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 2 tools", () => {
    expect(gitignoreTools).toHaveLength(2);
  });

  it("has no duplicate tool names", () => {
    const names = gitignoreTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_gitignore_get_all_templates", () => {
    const tool = gitignoreTools.find((t: any) => t.name === "github_gitignore_get_all_templates")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_gitignore_get_all_templates");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({  });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_gitignore_get_template", () => {
    const tool = gitignoreTools.find((t: any) => t.name === "github_gitignore_get_template")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_gitignore_get_template");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ name: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
