// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { hostedComputeTools } from "../../tools/hosted-compute.js";

const mockRequest = vi.mocked(githubRequest);

describe("hostedComputeTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 6 tools", () => {
    expect(hostedComputeTools).toHaveLength(6);
  });

  it("has no duplicate tool names", () => {
    const names = hostedComputeTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_hosted_compute_list_network_configurations_for_org", () => {
    const tool = hostedComputeTools.find((t: any) => t.name === "github_hosted_compute_list_network_configurations_for_org")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_hosted_compute_list_network_configurations_for_org");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", per_page: 1, page: 1 });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_hosted_compute_create_network_configuration_for_org", () => {
    const tool = hostedComputeTools.find((t: any) => t.name === "github_hosted_compute_create_network_configuration_for_org")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_hosted_compute_create_network_configuration_for_org");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

  describe("github_hosted_compute_get_network_configuration_for_org", () => {
    const tool = hostedComputeTools.find((t: any) => t.name === "github_hosted_compute_get_network_configuration_for_org")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_hosted_compute_get_network_configuration_for_org");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", network_configuration_id: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
