// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { interactionsTools } from "../../tools/interactions.js";

const mockRequest = vi.mocked(githubRequest);

describe("interactionsTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 9 tools", () => {
    expect(interactionsTools).toHaveLength(9);
  });

  it("has no duplicate tool names", () => {
    const names = interactionsTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_interactions_get_restrictions_for_org", () => {
    const tool = interactionsTools.find((t: any) => t.name === "github_interactions_get_restrictions_for_org")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_interactions_get_restrictions_for_org");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_interactions_set_restrictions_for_org", () => {
    const tool = interactionsTools.find((t: any) => t.name === "github_interactions_set_restrictions_for_org")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_interactions_set_restrictions_for_org");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("PUT");
    });
  });

  describe("github_interactions_remove_restrictions_for_org", () => {
    const tool = interactionsTools.find((t: any) => t.name === "github_interactions_remove_restrictions_for_org")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_interactions_remove_restrictions_for_org");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("DELETE");
    });
  });

});
