// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { licensesTools } from "../../tools/licenses.js";

const mockRequest = vi.mocked(githubRequest);

describe("licensesTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 3 tools", () => {
    expect(licensesTools).toHaveLength(3);
  });

  it("has no duplicate tool names", () => {
    const names = licensesTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_licenses_get_all_commonly_used", () => {
    const tool = licensesTools.find((t: any) => t.name === "github_licenses_get_all_commonly_used")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_licenses_get_all_commonly_used");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ featured: true, per_page: 1 });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_licenses_get", () => {
    const tool = licensesTools.find((t: any) => t.name === "github_licenses_get")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_licenses_get");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ license: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_licenses_get_for_repo", () => {
    const tool = licensesTools.find((t: any) => t.name === "github_licenses_get_for_repo")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_licenses_get_for_repo");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
