// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { oidcTools } from "../../tools/oidc.js";

const mockRequest = vi.mocked(githubRequest);

describe("oidcTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 8 tools", () => {
    expect(oidcTools).toHaveLength(8);
  });

  it("has no duplicate tool names", () => {
    const names = oidcTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_oidc_list_oidc_custom_property_inclusions_for_enterprise", () => {
    const tool = oidcTools.find((t: any) => t.name === "github_oidc_list_oidc_custom_property_inclusions_for_enterprise")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_oidc_list_oidc_custom_property_inclusions_for_enterprise");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_oidc_create_oidc_custom_property_inclusion_for_enterprise", () => {
    const tool = oidcTools.find((t: any) => t.name === "github_oidc_create_oidc_custom_property_inclusion_for_enterprise")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_oidc_create_oidc_custom_property_inclusion_for_enterprise");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

  describe("github_oidc_delete_oidc_custom_property_inclusion_for_enterprise", () => {
    const tool = oidcTools.find((t: any) => t.name === "github_oidc_delete_oidc_custom_property_inclusion_for_enterprise")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_oidc_delete_oidc_custom_property_inclusion_for_enterprise");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ enterprise: "test-value", custom_property_name: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("DELETE");
    });
  });

});
