// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { packagesTools } from "../../tools/packages.js";

const mockRequest = vi.mocked(githubRequest);

describe("packagesTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 27 tools", () => {
    expect(packagesTools).toHaveLength(27);
  });

  it("has no duplicate tool names", () => {
    const names = packagesTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_packages_list_docker_migration_conflicting_packages_for_organization", () => {
    const tool = packagesTools.find((t: any) => t.name === "github_packages_list_docker_migration_conflicting_packages_for_organization")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_packages_list_docker_migration_conflicting_packages_for_organization");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_packages_list_packages_for_organization", () => {
    const tool = packagesTools.find((t: any) => t.name === "github_packages_list_packages_for_organization")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_packages_list_packages_for_organization");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_packages_get_package_for_organization", () => {
    const tool = packagesTools.find((t: any) => t.name === "github_packages_get_package_for_organization")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_packages_get_package_for_organization");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", package_type: "test-value", package_name: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
