// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { privateRegistriesTools } from "../../tools/private-registries.js";

const mockRequest = vi.mocked(githubRequest);

describe("privateRegistriesTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 6 tools", () => {
    expect(privateRegistriesTools).toHaveLength(6);
  });

  it("has no duplicate tool names", () => {
    const names = privateRegistriesTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_private_registries_list_org_private_registries", () => {
    const tool = privateRegistriesTools.find((t: any) => t.name === "github_private_registries_list_org_private_registries")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_private_registries_list_org_private_registries");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", per_page: 1, page: 1 });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_private_registries_create_org_private_registry", () => {
    const tool = privateRegistriesTools.find((t: any) => t.name === "github_private_registries_create_org_private_registry")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_private_registries_create_org_private_registry");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

  describe("github_private_registries_get_org_public_key", () => {
    const tool = privateRegistriesTools.find((t: any) => t.name === "github_private_registries_get_org_public_key")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_private_registries_get_org_public_key");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
