// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { reactionsTools } from "../../tools/reactions.js";

const mockRequest = vi.mocked(githubRequest);

describe("reactionsTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 15 tools", () => {
    expect(reactionsTools).toHaveLength(15);
  });

  it("has no duplicate tool names", () => {
    const names = reactionsTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_reactions_list_for_commit_comment", () => {
    const tool = reactionsTools.find((t: any) => t.name === "github_reactions_list_for_commit_comment")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_reactions_list_for_commit_comment");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", comment_id: "test-value", per_page: 1 });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_reactions_create_for_commit_comment", () => {
    const tool = reactionsTools.find((t: any) => t.name === "github_reactions_create_for_commit_comment")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_reactions_create_for_commit_comment");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", comment_id: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("POST");
    });
  });

  describe("github_reactions_delete_for_commit_comment", () => {
    const tool = reactionsTools.find((t: any) => t.name === "github_reactions_delete_for_commit_comment")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_reactions_delete_for_commit_comment");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ owner: "test-value", repo: "test-value", comment_id: "test-value", reaction_id: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("DELETE");
    });
  });

});
