// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { secretScanningTools } from "../../tools/secret-scanning.js";

const mockRequest = vi.mocked(githubRequest);

describe("secretScanningTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 9 tools", () => {
    expect(secretScanningTools).toHaveLength(9);
  });

  it("has no duplicate tool names", () => {
    const names = secretScanningTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_secret_scanning_list_alerts_for_org", () => {
    const tool = secretScanningTools.find((t: any) => t.name === "github_secret_scanning_list_alerts_for_org")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_secret_scanning_list_alerts_for_org");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", secret_type: "test" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_secret_scanning_list_org_pattern_configs", () => {
    const tool = secretScanningTools.find((t: any) => t.name === "github_secret_scanning_list_org_pattern_configs")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_secret_scanning_list_org_pattern_configs");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_secret_scanning_update_org_pattern_configs", () => {
    const tool = secretScanningTools.find((t: any) => t.name === "github_secret_scanning_update_org_pattern_configs")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_secret_scanning_update_org_pattern_configs");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value", body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("PATCH");
    });
  });

});
