// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { securityAdvisoriesTools } from "../../tools/security-advisories.js";

const mockRequest = vi.mocked(githubRequest);

describe("securityAdvisoriesTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 10 tools", () => {
    expect(securityAdvisoriesTools).toHaveLength(10);
  });

  it("has no duplicate tool names", () => {
    const names = securityAdvisoriesTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_security_advisories_list_global_advisories", () => {
    const tool = securityAdvisoriesTools.find((t: any) => t.name === "github_security_advisories_list_global_advisories")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_security_advisories_list_global_advisories");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ ghsa_id: "test" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_security_advisories_get_global_advisory", () => {
    const tool = securityAdvisoriesTools.find((t: any) => t.name === "github_security_advisories_get_global_advisory")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_security_advisories_get_global_advisory");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ ghsa_id: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_security_advisories_list_org_repository_advisories", () => {
    const tool = securityAdvisoriesTools.find((t: any) => t.name === "github_security_advisories_list_org_repository_advisories")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_security_advisories_list_org_repository_advisories");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ org: "test-value" });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
