// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../client.js", () => ({
  githubRequest: vi.fn().mockResolvedValue({ success: true }),
}));

import { githubRequest } from "../../client.js";
import { usersTools } from "../../tools/users.js";

const mockRequest = vi.mocked(githubRequest);

describe("usersTools", () => {
  beforeEach(() => { mockRequest.mockClear(); });

  it("exports 47 tools", () => {
    expect(usersTools).toHaveLength(47);
  });

  it("has no duplicate tool names", () => {
    const names = usersTools.map((t: any) => t.name);
    expect(new Set(names).size).toBe(names.length);
  });

  describe("github_users_get_authenticated", () => {
    const tool = usersTools.find((t: any) => t.name === "github_users_get_authenticated")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_users_get_authenticated");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({  });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

  describe("github_users_update_authenticated", () => {
    const tool = usersTools.find((t: any) => t.name === "github_users_update_authenticated")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_users_update_authenticated");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ body: { test: true } });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("PATCH");
    });
  });

  describe("github_users_list_blocked_by_authenticated_user", () => {
    const tool = usersTools.find((t: any) => t.name === "github_users_list_blocked_by_authenticated_user")!;

    it("exists and has required properties", () => {
      expect(tool).toBeDefined();
      expect(tool.name).toBe("github_users_list_blocked_by_authenticated_user");
      expect(tool.description).toBeTruthy();
      expect(tool.inputSchema).toBeDefined();
      expect(tool.handler).toBeInstanceOf(Function);
    });

    it("calls githubRequest", async () => {
      await tool.handler({ per_page: 1, page: 1 });
      expect(mockRequest).toHaveBeenCalledTimes(1);
      expect(mockRequest.mock.calls[0][0]).toBe("GET");
    });
  });

});
