#!/usr/bin/env node
// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { actionsTools } from "./tools/actions.js";
import { activityTools } from "./tools/activity.js";
import { agentTasksTools } from "./tools/agent-tasks.js";
import { appsTools } from "./tools/apps.js";
import { billingTools } from "./tools/billing.js";
import { campaignsTools } from "./tools/campaigns.js";
import { checksTools } from "./tools/checks.js";
import { classroomTools } from "./tools/classroom.js";
import { codeScanningTools } from "./tools/code-scanning.js";
import { codeSecurityTools } from "./tools/code-security.js";
import { codesOfConductTools } from "./tools/codes-of-conduct.js";
import { codespacesTools } from "./tools/codespaces.js";
import { copilotTools } from "./tools/copilot.js";
import { credentialsTools } from "./tools/credentials.js";
import { dependabotTools } from "./tools/dependabot.js";
import { dependencyGraphTools } from "./tools/dependency-graph.js";
import { emojisTools } from "./tools/emojis.js";
import { enterpriseTeamMembershipsTools } from "./tools/enterprise-team-memberships.js";
import { enterpriseTeamOrganizationsTools } from "./tools/enterprise-team-organizations.js";
import { enterpriseTeamsTools } from "./tools/enterprise-teams.js";
import { gistsTools } from "./tools/gists.js";
import { gitTools } from "./tools/git.js";
import { gitignoreTools } from "./tools/gitignore.js";
import { hostedComputeTools } from "./tools/hosted-compute.js";
import { interactionsTools } from "./tools/interactions.js";
import { issuesTools } from "./tools/issues.js";
import { licensesTools } from "./tools/licenses.js";
import { markdownTools } from "./tools/markdown.js";
import { metaTools } from "./tools/meta.js";
import { migrationsTools } from "./tools/migrations.js";
import { oidcTools } from "./tools/oidc.js";
import { orgsTools } from "./tools/orgs.js";
import { packagesTools } from "./tools/packages.js";
import { privateRegistriesTools } from "./tools/private-registries.js";
import { projectsTools } from "./tools/projects.js";
import { pullsTools } from "./tools/pulls.js";
import { rateLimitTools } from "./tools/rate-limit.js";
import { reactionsTools } from "./tools/reactions.js";
import { reposTools } from "./tools/repos.js";
import { searchTools } from "./tools/search.js";
import { secretScanningTools } from "./tools/secret-scanning.js";
import { securityAdvisoriesTools } from "./tools/security-advisories.js";
import { teamsTools } from "./tools/teams.js";
import { usersTools } from "./tools/users.js";

const server = new McpServer({
  name: "github-mcp",
  version: "1.0.0",
});

const allToolModules = [
  { category: "actions", tools: actionsTools },
  { category: "activity", tools: activityTools },
  { category: "agent-tasks", tools: agentTasksTools },
  { category: "apps", tools: appsTools },
  { category: "billing", tools: billingTools },
  { category: "campaigns", tools: campaignsTools },
  { category: "checks", tools: checksTools },
  { category: "classroom", tools: classroomTools },
  { category: "code-scanning", tools: codeScanningTools },
  { category: "code-security", tools: codeSecurityTools },
  { category: "codes-of-conduct", tools: codesOfConductTools },
  { category: "codespaces", tools: codespacesTools },
  { category: "copilot", tools: copilotTools },
  { category: "credentials", tools: credentialsTools },
  { category: "dependabot", tools: dependabotTools },
  { category: "dependency-graph", tools: dependencyGraphTools },
  { category: "emojis", tools: emojisTools },
  { category: "enterprise-team-memberships", tools: enterpriseTeamMembershipsTools },
  { category: "enterprise-team-organizations", tools: enterpriseTeamOrganizationsTools },
  { category: "enterprise-teams", tools: enterpriseTeamsTools },
  { category: "gists", tools: gistsTools },
  { category: "git", tools: gitTools },
  { category: "gitignore", tools: gitignoreTools },
  { category: "hosted-compute", tools: hostedComputeTools },
  { category: "interactions", tools: interactionsTools },
  { category: "issues", tools: issuesTools },
  { category: "licenses", tools: licensesTools },
  { category: "markdown", tools: markdownTools },
  { category: "meta", tools: metaTools },
  { category: "migrations", tools: migrationsTools },
  { category: "oidc", tools: oidcTools },
  { category: "orgs", tools: orgsTools },
  { category: "packages", tools: packagesTools },
  { category: "private-registries", tools: privateRegistriesTools },
  { category: "projects", tools: projectsTools },
  { category: "pulls", tools: pullsTools },
  { category: "rate-limit", tools: rateLimitTools },
  { category: "reactions", tools: reactionsTools },
  { category: "repos", tools: reposTools },
  { category: "search", tools: searchTools },
  { category: "secret-scanning", tools: secretScanningTools },
  { category: "security-advisories", tools: securityAdvisoriesTools },
  { category: "teams", tools: teamsTools },
  { category: "users", tools: usersTools },
];

const enabledCategories = process.env.GITHUB_MCP_CATEGORIES
  ? new Set(process.env.GITHUB_MCP_CATEGORIES.split(",").map((s) => s.trim()))
  : null;

const allTools = allToolModules
  .filter((m) => !enabledCategories || enabledCategories.has(m.category))
  .flatMap((m) => m.tools);

for (const tool of allTools) {
  server.tool(
    tool.name,
    tool.description,
    tool.inputSchema.shape as any,
    async (args: any) => {
      try {
        const result = await tool.handler(args as any);
        return {
          content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
        };
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text" as const, text: `Error: ${message}` }],
          isError: true,
        };
      }
    }
  );
}

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(`GitHub MCP server running (${allTools.length} tools registered)`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
